"use client";
export type Readiness = { storage: boolean; background: boolean; scheduler: boolean; ai: boolean; aiProvider: string; pagespeed: boolean; google: boolean };
export default function IntegrationSetup({ readiness, profileId }: { readiness: Readiness; profileId: string }) {
  const steps = [
    { title: "Site-wide background audits", ready: readiness.background, lines: ["Use a private production Redis database, separate from Preview. Keep the project on a free plan and monitor its quota.", "In Vercel → Project → Settings → Environment Variables, configure production UPSTASH_REDIS_REST_URL and UPSTASH_REDIS_REST_TOKEN, then SEO_BACKGROUND_ENABLED=true.", "Redeploy. Start with 10 pages and verify that a completed audit appears in Saved audits. Increase the cap only after that test; maximum 500 pages per audit."] },
    { title: "Daily or weekly repeats", ready: readiness.scheduler, lines: ["In Vercel production environment variables add CRON_SECRET with a randomly generated value of at least 32 characters. Keep it private.", "Redeploy, complete one audit, then choose Repeat weekly or Repeat daily. The free Hobby cron checks due schedules once daily; start times may vary within its scheduled hour.", "Check Next due, last job and deployment cron logs to confirm an actual run. Stop repeats below whenever needed."] },
    { title: "Free AI content assessment", ready: readiness.ai, lines: ["Create a Gemini API key in Google AI Studio using a project with billing disabled. Confirm the selected model is offered in the free tier for your region.", "Set SEO_AI_PROVIDER=gemini, GEMINI_API_KEY, GEMINI_MODEL=gemini-2.5-flash-lite and SEO_GEMINI_FREE_TIER_CONFIRMED=true in Vercel. Keep SEO_ALLOW_PAID_AI=false. Redeploy and run one AI review.", "The app never falls back to a paid provider. Google free-tier inputs may be used to improve products. Do not submit confidential content. The public report also offers a manual prompt without an API key."] },
    { title: "Real traffic and search data", ready: readiness.google, lines: ["For the free immediate route, export Search Console or GA4 CSV data and import it in the public report’s Traffic & value tab.", "For automatic retrieval, enable Search Console API and Google Analytics Data API in your Google Cloud project. Create a service account and give it read access to the appropriate Search Console and GA4 properties.", "Save its credential JSON in GOOGLE_SERVICE_ACCOUNT_JSON in Vercel. Never post the key in chat or GitHub. Set SEO_GOOGLE_PROPERTIES_JSON with the exact website hostname, property IDs and authorized profile ID, then redeploy.", `Your authorized profile ID: ${profileId}`, 'Mapping format: {"www.example.com":{"gsc":"sc-domain:example.com","ga4":"123456789","allowedProfileIds":["YOUR_PROFILE_ID"]}}', "Run Fetch Google data on the matching saved audit and verify the property/date labels. Empty data is not zero traffic."] },
    { title: "Real loading-speed measurements", ready: readiness.pagespeed, lines: ["Use the PageSpeed Insights link in the report at no charge. To enable in-app measurements, enable the PageSpeed Insights API in Google Cloud and add PAGESPEED_API_KEY in Vercel, then redeploy.", "Test one public URL. Field data can be unavailable for low-traffic pages; HTML delivery checks are not Core Web Vitals."] },
  ];
  return <section className="space-y-3 rounded-xl border border-slate-700 p-5"><h2 className="text-xl font-bold">Connections and setup</h2><p>These labels check configuration presence, not provider health. A real successful run is still required. Keep all keys in Vercel, never in chat or source code.</p>{steps.map((step, i) => <details key={step.title} className="rounded-lg border border-slate-700 p-4"><summary className="cursor-pointer font-semibold">{i + 1}. {step.title} — {step.ready ? "Configured; verify with a real run" : "Setup needed"}</summary><ol className="mt-3 list-decimal space-y-2 pl-5">{step.lines.map(line => <li key={line} className="break-words">{line}</li>)}</ol></details>)}</section>;
}
