"use client";
import { useEffect, useState } from "react";
import type { SignedReport } from "@/lib/seo/types";
import { recoveryCandidate, recoveryKey, recoveryLimit } from "@/lib/seo/report-recovery";
export default function ReportRecovery({ signed, onRestore }: { signed: SignedReport | null; onRestore: (signed: SignedReport) => void }) {
  const [saved, setSaved] = useState<SignedReport | null>(null);
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);
  useEffect(() => { try { const raw = localStorage.getItem(recoveryKey); if (raw) { const candidate = recoveryCandidate(raw); setSaved(candidate); if (!candidate) { localStorage.removeItem(recoveryKey); setNotice("The saved report expired or is invalid. Run a fresh audit."); } } } catch { setNotice("Browser storage is unavailable. Download your PDF instead."); } }, []);
  function save() { if (!signed) return; try { const raw = JSON.stringify(signed); if (raw.length > recoveryLimit) throw new Error("This report is too large for browser recovery. Download the PDF."); localStorage.setItem(recoveryKey, raw); setSaved(signed); setNotice("Report saved on this device. You can reopen it until its original expiry."); } catch (e) { setNotice(e instanceof Error ? e.message : "Could not save the report."); } }
  async function restore() { if (!saved) return; setBusy(true); setNotice(""); try { const response = await fetch("/api/seo/restore", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(saved) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Report could not be verified."); onRestore(data.signed); setNotice("Saved report reopened and signature verified. These are historical findings, not a fresh crawl."); } catch (e) { setNotice(e instanceof Error ? e.message : "Report could not reopen."); } finally { setBusy(false); } }
  function remove() { try { localStorage.removeItem(recoveryKey); setSaved(null); setNotice("Saved copy removed from this browser."); } catch { setNotice("Browser storage is unavailable."); } }
  return <section className="hg-wrap hg-panel" aria-label="Saved report recovery"><h2>Keep your report handy.</h2><p>Save one audit on this browser for up to 24 hours from its original creation. Saving replaces the previous copy. Shared devices can access this copy. Traffic CSVs, business calculations and drafts are not saved.</p><div className="flex flex-wrap gap-3">{signed && <button className="hg-button hg-button-outline" onClick={save}>Save report on this device</button>}{saved && <><button className="hg-button hg-button-primary" disabled={busy} onClick={restore}>{busy ? "Verifying report…" : "Reopen saved report"}</button><button className="hg-button hg-button-quiet" disabled={busy} onClick={remove}>Remove saved copy</button></>}</div>{saved && <p className="hg-note">Saved website: {saved.report.input.url} · Expires: {new Date(saved.report.expiresAt).toLocaleString()}</p>}{notice && <p role="status">{notice}</p>}</section>;
}
