import type { CaseStudyData } from "@/types";

/**
 * Case studies seeded from HaadinGlobal's real project list and real
 * results screenshots (migrated from the previous site). Nothing here is
 * invented: project facts come from the old portfolio page and every metric
 * matches a screenshot in /public/images/results. Client names for the
 * results galleries are withheld, as on the previous site.
 *
 * Add verified numbers (before/after, metrics) from /admin/case-studies.
 */
export const CASE_STUDIES: CaseStudyData[] = [
  {
    slug: "organic-search-growth",
    title: "Organic Search Growth Across Client Sites",
    client: "Multiple clients (names withheld)",
    industry: "Various",
    country: "International",
    service: "Technical SEO & Content",
    tags: ["seo"],
    problem: "Client websites with little or no organic visibility, relying entirely on paid traffic or referrals.",
    strategy: "Technical fixes, keyword-to-page mapping, content built around real search questions and steady authority building.",
    result: "Search Console and Analytics data from client properties show sustained growth in clicks, impressions and visitors.",
    headlineValue: "329K",
    headlineLabel: "Google Search clicks (3 months)",
    metrics: [
      { label: "Clicks / impressions (3-month period)", value: "329K / 50.6M" },
      { label: "Organic growth, another client", value: "19.8K clicks · 1.77M impressions" },
      { label: "Website visitors (Google Analytics)", value: "+413%" },
      { label: "New site average position", value: "4.9" },
    ],
    beforeAfter: null,
    coverImage: "/images/results/seo-329k.png",
    gallery: [
      { src: "/images/results/seo-329k.png", caption: "329K clicks & 50.6M impressions from Google Search (3-month period)" },
      { src: "/images/results/seo-177m.png", caption: "Organic growth to 19.8K clicks & 1.77M impressions" },
      { src: "/images/results/seo-589k.png", caption: "Steady SEO climb — 4.63K clicks, avg position 7.1" },
      { src: "/images/results/seo-682k.png", caption: "From near-zero to 5.91K clicks & 682K impressions" },
      { src: "/images/results/seo-pos49.png", caption: "New site breakout — avg position 4.9 within weeks" },
      { src: "/images/results/seo-ga4.png", caption: "Website visitors up 413% (Google Analytics)" },
    ],
    liveUrl: null,
    isPlaceholder: false,
    sortOrder: 1,
  },
  {
    slug: "google-ads-performance-max",
    title: "Google Ads & Performance Max Results",
    client: "Multiple clients (names withheld)",
    industry: "eCommerce & Lead Generation",
    country: "International",
    service: "Google Ads & Performance Max",
    tags: ["google", "ecommerce"],
    problem: "Ad accounts spending without clear conversion tracking or a structure that let the budget follow profitable searches.",
    strategy: "Clean conversion tracking, segmented Performance Max asset groups and ongoing search-term and bid management.",
    result: "Screenshots from live Google Ads accounts show strong return on ad spend and conversion volume.",
    headlineValue: "9.7x",
    headlineLabel: "Performance Max ROAS",
    metrics: [
      { label: "Performance Max ROAS", value: "9.7x" },
      { label: "$14K spend → conversion value", value: "$58.8K (4.2x)" },
      { label: "Conversions driven", value: "71.5K (+584%)" },
      { label: "Cost per conversion", value: "$14.79" },
    ],
    beforeAfter: null,
    coverImage: "/images/results/gads-roas97.png",
    gallery: [
      { src: "/images/results/gads-roas97.png", caption: "Performance Max: 9.7x return on ad spend" },
      { src: "/images/results/gads-roas42.png", caption: "Performance Max: $14K spend → $58.8K conversion value (4.2x ROAS)" },
      { src: "/images/results/gads-71k.png", caption: "71.5K conversions driven (+584% period-on-period)" },
      { src: "/images/results/gads-109.png", caption: "109 conversions at just $14.79 cost per conversion" },
    ],
    liveUrl: null,
    isPlaceholder: false,
    sortOrder: 2,
  },
  {
    slug: "tiktok-ads-reach",
    title: "TikTok Ads Reach & Engagement",
    client: "Client name withheld",
    industry: "Consumer brand",
    country: "International",
    service: "TikTok Ads",
    tags: ["tiktok"],
    problem: "A consumer brand needing affordable reach with a younger audience.",
    strategy: "Native, UGC-style creatives with rapid hook testing.",
    result: "6.8M impressions with a 19.6% click-through rate, per the TikTok Ads dashboard.",
    headlineValue: "6.8M",
    headlineLabel: "Impressions",
    metrics: [
      { label: "Impressions", value: "6.8M" },
      { label: "Click-through rate", value: "19.6%" },
    ],
    beforeAfter: null,
    coverImage: "/images/results/tiktok-68m.png",
    gallery: [{ src: "/images/results/tiktok-68m.png", caption: "TikTok Ads: 6.8M impressions at 19.6% CTR" }],
    liveUrl: null,
    isPlaceholder: false,
    sortOrder: 3,
  },
  {
    slug: "ecommerce-store-sales",
    title: "eCommerce Store Sales",
    client: "Client name withheld",
    industry: "eCommerce",
    country: "International",
    service: "eCommerce & Paid Campaigns",
    tags: ["ecommerce", "meta"],
    problem: "A new online store that needed its first consistent sales.",
    strategy: "Store optimisation paired with paid campaigns driving qualified traffic.",
    result: "$13.5K revenue across 232 sales, per the store dashboard.",
    headlineValue: "$13.5K",
    headlineLabel: "Revenue · 232 sales",
    metrics: [
      { label: "Revenue", value: "$13.5K" },
      { label: "Sales", value: "232" },
    ],
    beforeAfter: null,
    coverImage: "/images/results/ecom-revenue.png",
    gallery: [
      { src: "/images/results/ecom-revenue.png", caption: "eCommerce store — $13.5K revenue across 232 sales" },
      { src: "/images/results/ecom-orders.png", caption: "Live store orders coming in from campaigns" },
    ],
    liveUrl: null,
    isPlaceholder: false,
    sortOrder: 4,
  },
  {
    slug: "kaashan-shopify",
    title: "Shopify Store for a Growing Clothing Brand",
    client: "Kaashan",
    industry: "Fashion & Apparel",
    country: "Pakistan",
    service: "Shopify Development",
    tags: ["ecommerce", "web"],
    problem: "A growing clothing brand needed a store built to browse and sell on mobile.",
    strategy: "Shopify store design and setup with conversion-focused product pages.",
    result: "Conversion-focused product pages and a clean, mobile-first storefront.",
    headlineValue: null,
    headlineLabel: null,
    metrics: [],
    beforeAfter: null,
    coverImage: null,
    gallery: [],
    liveUrl: "https://www.kaashan.com",
    isPlaceholder: false,
    sortOrder: 5,
  },
  {
    slug: "royal-painter-dubai",
    title: "Lead-Focused Website & Google Ads in Dubai",
    client: "Royal Painter Dubai",
    industry: "Home Services",
    country: "UAE",
    service: "Web Development, SEO & Google Ads",
    tags: ["gulf", "web", "google"],
    problem: "A painting-services company in Dubai needed a way to capture local 'near me' searches.",
    strategy: "Landing page and brand logo, on-page SEO and a Google Ads setup for the Dubai market.",
    result: "Lead-focused site with WhatsApp & call CTAs, built to capture 'near me' searches.",
    headlineValue: null,
    headlineLabel: null,
    metrics: [],
    beforeAfter: null,
    coverImage: null,
    gallery: [],
    liveUrl: "https://royalpainterdubai.com",
    isPlaceholder: false,
    sortOrder: 6,
  },
  {
    slug: "core-sportswears-catalogue",
    title: "Digital Catalogue with WhatsApp Ordering",
    client: "Core Sportswears",
    industry: "Manufacturing & Export",
    country: "Pakistan",
    service: "Web Development",
    tags: ["web"],
    problem: "Buyers needed an easy way to browse product lines and place custom-order enquiries.",
    strategy: "Digital catalogue & flipbook website (ski & snow wear, streetwear, sportswear, bags) with PDF download and WhatsApp ordering.",
    result: "One-tap catalogue browsing and instant WhatsApp enquiries for custom orders.",
    headlineValue: null,
    headlineLabel: null,
    metrics: [],
    beforeAfter: null,
    coverImage: null,
    gallery: [],
    liveUrl: "https://catalogue-nine-brown.vercel.app",
    isPlaceholder: false,
    sortOrder: 7,
  },
  {
    slug: "abdulla-events-seo",
    title: "Event-Rental Website & SEO Foundation",
    client: "Abdulla Events",
    industry: "Events",
    country: "Saudi Arabia",
    service: "Web Development & SEO",
    tags: ["gulf", "seo", "web"],
    problem: "An event-rental business needed visibility for Saudi event-rental searches.",
    strategy: "Website for tables, chairs, tents, qahwa service and full event setups, plus an SEO foundation.",
    result: "Website development plus an SEO foundation — in progress.",
    headlineValue: null,
    headlineLabel: null,
    metrics: [],
    beforeAfter: null,
    coverImage: null,
    gallery: [],
    liveUrl: null,
    isPlaceholder: false,
    sortOrder: 8,
  },
  {
    slug: "royal-school-management-system",
    title: "Custom School Management System",
    client: "Royal International School System",
    industry: "Education",
    country: "Pakistan",
    service: "Custom Software",
    tags: ["web", "ai"],
    problem: "A school needed its own system for admissions, classes and student records.",
    strategy: "Custom-built school management system with admissions, class & student management and dashboards.",
    result: "Full data ownership and a self-serve dashboard built to the school's requirements. Live demo on request.",
    headlineValue: null,
    headlineLabel: null,
    metrics: [],
    beforeAfter: null,
    coverImage: null,
    gallery: [],
    liveUrl: null,
    isPlaceholder: false,
    sortOrder: 9,
  },
  {
    slug: "isp-management-portal",
    title: "ISP Management Portal",
    client: "Internet Service Provider (private)",
    industry: "Telecom",
    country: "Pakistan",
    service: "Custom Software",
    tags: ["web", "ai"],
    problem: "Customers, packages and billing were managed across separate tools.",
    strategy: "Custom management portal bringing customers, packages and billing into one place.",
    result: "A single dashboard to run day-to-day ISP operations. Live demo on request.",
    headlineValue: null,
    headlineLabel: null,
    metrics: [],
    beforeAfter: null,
    coverImage: null,
    gallery: [],
    liveUrl: null,
    isPlaceholder: false,
    sortOrder: 10,
  },
  {
    slug: "markhor-college-local-seo",
    title: "Google Business Profile for a College",
    client: "Markhor College",
    industry: "Education",
    country: "Pakistan",
    service: "Local SEO",
    tags: ["seo"],
    problem: "Low local visibility for 'college in Sahiwal' style searches.",
    strategy: "Google Business Profile optimisation — categories, information and local presence.",
    result: "Stronger local visibility for 'college in Sahiwal' style searches.",
    headlineValue: null,
    headlineLabel: null,
    metrics: [],
    beforeAfter: null,
    coverImage: null,
    gallery: [],
    liveUrl: "https://markhorcollege.com",
    isPlaceholder: false,
    sortOrder: 11,
  },
];
