import type { PricingPlanData } from "@/types";

/** Default retainer tiers (Stitch "Verified Retainers"). Editable in /admin/pricing once seeded. */
export const DEFAULT_PRICING_PLANS: PricingPlanData[] = [
  {
    slug: "starter",
    name: "STARTER",
    eyebrow: "Foundation",
    description: "Ideal for early-stage startups and localized business footprints needing stable discoverability.",
    price: 15000,
    billingPeriod: "month",
    projectDiscount: 10,
    features: [
      "Meta & Facebook page operations",
      "12 designed social posts",
      "Essential creative design & monthly performance brief",
      "Foundational on-page SEO checks",
    ],
    serviceLimits: "1 ad platform · 12 posts / month",
    popular: false,
    variant: "STANDARD",
    ctaLabel: "Select Starter Plan",
    whatsappMessage: "Hello HaadinGlobal, I am interested in the Starter plan.",
    sortOrder: 1,
  },
  {
    slug: "growth",
    name: "GROWTH",
    eyebrow: "Velocity",
    description: "Client acquisition engine for scaling brands seeking an omnichannel presence.",
    price: 35000,
    billingPeriod: "month",
    projectDiscount: 10,
    features: [
      "Meta Ads & Google Ads combined execution",
      "20 multi-format posts + animated stories",
      "Email drip campaigns",
      "Keyword tracking & bi-weekly sync",
    ],
    serviceLimits: "2 ad platforms · 20 posts / month",
    popular: true,
    variant: "POPULAR",
    ctaLabel: "Deploy Growth Suite",
    whatsappMessage: "Hello HaadinGlobal, I am ready to start the Growth plan.",
    sortOrder: 2,
  },
  {
    slug: "pro",
    name: "PRO",
    eyebrow: "Enterprise Inbound",
    description: "Full-stack content and paid-media unit with rapid short-form video production.",
    price: 70000,
    billingPeriod: "month",
    projectDiscount: 10,
    features: [
      "30 posts + Reels & TikTok edits",
      "Technical SEO & backlink sprint",
      "WhatsApp Business API setup & retargeting",
      "Weekly dashboards & rapid creatives",
    ],
    serviceLimits: "3 ad platforms · 30 posts / month",
    popular: false,
    variant: "STANDARD",
    ctaLabel: "Select Pro Plan",
    whatsappMessage: "Hello HaadinGlobal, I am interested in the Pro plan.",
    sortOrder: 3,
  },
  {
    slug: "premium",
    name: "PREMIUM",
    eyebrow: "Global Expansion",
    description: "Dedicated growth manager, AI integrations, and full eCommerce infrastructure.",
    price: 120000,
    billingPeriod: "month",
    projectDiscount: 10,
    features: [
      "Dedicated growth manager on speed-dial",
      "End-to-end AI automation & CRM pipelines",
      "Shopify / web app conversion optimisation",
      "Influencer outreach & brand syndication",
    ],
    serviceLimits: "All channels · custom scope",
    popular: false,
    variant: "PREMIUM",
    ctaLabel: "Book Premium Consultation",
    whatsappMessage: "Hello HaadinGlobal, let us schedule a Premium retainer brief.",
    sortOrder: 4,
  },
];

export const PRICING_GUARANTEES = [
  { icon: "lock_open", title: "No Onboarding Fees", description: "We don't charge setup or onboarding fees. Your budget goes into media and execution." },
  { icon: "schedule", title: "Month-to-Month Agility", description: "No long lock-in contracts. Monthly retainers renew every 30 days." },
  { icon: "query_stats", title: "Bi-Weekly Performance Reviews", description: "Regular reviews of your numbers with the strategist running your account." },
  { icon: "forum", title: "Direct WhatsApp Desk", description: "Direct communication with the team — no ticket queues." },
] as const;
