import type { ServiceData } from "@/types";

/**
 * Default service catalogue. Used to seed the database (prisma/seed.ts) and
 * as a read-only fallback when the database is unreachable. Once seeded,
 * edit services from /admin/services — the database is the source of truth.
 * Prices are in PKR and mirror the Stitch design.
 */
export const DEFAULT_SERVICES: ServiceData[] = [
  {
    slug: "meta-ads",
    title: "Meta Ads",
    tagline: "Performance Marketing",
    category: "PERFORMANCE",
    icon: "ads_click",
    shortDescription:
      "High-converting Facebook & Instagram funnel campaigns, pixel tracking, dynamic retargeting & algorithmic creative testing.",
    description:
      "Stop burning ad budgets on boost buttons. We plan, build and manage Facebook and Instagram campaigns around your unit economics — with proper pixel and Conversions API tracking, structured creative testing and disciplined budget scaling — so every rupee or dollar is accountable to leads and sales.",
    price: 15000,
    priceUnit: "MONTH",
    highlights: ["CBO/ABO Testing", "Server-Side CAPI", "Weekly Reports"],
    features: [
      "Audience research & segmentation",
      "Meta Pixel + Conversions API setup",
      "Ad creative design (static, carousel & reels)",
      "Campaign architecture: prospecting vs. retargeting",
      "Catalogue & dynamic product ads",
      "Weekly performance reports",
    ],
    benefits: [
      "Accurate conversion tracking after iOS privacy changes",
      "Lower cost per lead through structured creative testing",
      "Clear reporting on spend, leads and return",
    ],
    process: [
      { title: "Audience & Pixel Audit", description: "Verify event match quality and map audience overlap before spending a rupee." },
      { title: "Creative Production", description: "Hook-driven static variations, carousels and short-form video built for testing." },
      { title: "Campaign Architecture", description: "Advantage+ and manual campaigns with clear budget splits for cold acquisition vs. remarketing." },
      { title: "Scaling & Daily Trimming", description: "Pause under-performing ad sets quickly and scale proven winners gradually." },
    ],
    faqs: [
      { question: "What ad budget do I need for Meta Ads?", answer: "For Pakistan we usually recommend starting with PKR 40k–80k per month in ad spend (separate from our management fee). For GCC, UK or US campaigns, $1,000–$2,500 per month is a sensible starting point." },
      { question: "How soon will I see results?", answer: "Campaigns typically start producing leads within 7–10 days of launch; performance improves as the algorithm learns and creatives are refined." },
    ],
    ctaLabel: "Book Meta Ads",
    whatsappMessage: "Hi HaadinGlobal, I'm interested in Meta Ads management.",
    seoTitle: "Meta Ads Management (Facebook & Instagram Ads)",
    seoDescription: "Facebook & Instagram ads management with Conversions API tracking, creative testing and weekly reporting. From PKR 15,000/month.",
    image: "/images/services/meta-ads.jpg",
    featured: true,
    inBuilder: true,
    builderLabel: "Meta Ads",
    sortOrder: 1,
  },
  {
    slug: "google-ads",
    title: "Google Ads",
    tagline: "Search & Omnichannel",
    category: "PERFORMANCE",
    icon: "campaign",
    shortDescription:
      "High-intent Google Search, Performance Max, Display Network, and Merchant Center Shopping setups with smart bid strategies.",
    description:
      "Capture buyers at the exact moment they search. We build Google Search, Performance Max, Shopping, Display and YouTube campaigns with clean conversion tracking, tight keyword control and bid strategies matched to your margins.",
    price: 25000,
    priceUnit: "MONTH",
    highlights: ["Negative Keyword Lists", "PMax Asset Groups", "ROAS Optimization"],
    features: [
      "Keyword research & intent mapping",
      "Search, Performance Max & Shopping campaigns",
      "Google Ads & GA4 conversion tracking",
      "Negative keyword management",
      "Ad copy & asset group testing",
      "Monthly performance reports",
    ],
    benefits: [
      "Traffic from people already searching for what you sell",
      "Less wasted spend on irrelevant searches",
      "Transparent cost-per-conversion reporting",
    ],
    process: [
      { title: "Account & Tracking Audit", description: "Review existing campaigns and fix conversion tracking first." },
      { title: "Keyword & Structure Plan", description: "Group keywords by intent and build a clean campaign structure." },
      { title: "Launch", description: "Go live with tested ad copy, assets and sensible bid strategies." },
      { title: "Optimise", description: "Weekly search-term pruning, bid adjustments and asset refreshes." },
    ],
    faqs: [
      { question: "Is the ad spend included in the price?", answer: "No. The price covers management; ad spend is paid directly to Google from your own account, so you keep full ownership and visibility." },
      { question: "Do you work with Performance Max?", answer: "Yes — for eCommerce and lead generation, with properly segmented asset groups and audience signals." },
    ],
    ctaLabel: "Scale with Google Ads",
    whatsappMessage: "Hi HaadinGlobal, tell me more about Google Ads management.",
    seoTitle: "Google Ads Management (Search, PMax & Shopping)",
    seoDescription: "Google Search, Performance Max and Shopping campaigns with clean tracking and ROAS-focused optimisation. From PKR 25,000/month.",
    image: null,
    featured: true,
    inBuilder: true,
    builderLabel: "Google Ads & PMax",
    sortOrder: 2,
  },
  {
    slug: "seo",
    title: "Technical SEO",
    tagline: "Organic Velocity",
    category: "PERFORMANCE",
    icon: "manage_search",
    shortDescription:
      "Technical audit fixes, schema markup, semantic keyword clusters, Core Web Vitals acceleration, and manual white-hat backlinks.",
    description:
      "Rank for the searches that bring customers. We combine technical SEO, keyword research, helpful content and white-hat link building to grow organic traffic that compounds month after month — locally and internationally.",
    price: 35000,
    priceUnit: "MONTH",
    highlights: ["Site Speed 90+", "Topical Authority", "Tier 1 Linkbuilding"],
    features: [
      "Technical SEO audit & fixes",
      "Keyword research & topic clusters",
      "On-page optimisation & schema markup",
      "Core Web Vitals improvements",
      "Content briefs & optimisation",
      "White-hat link building",
      "Google Business Profile optimisation",
    ],
    benefits: [
      "Sustainable traffic that doesn't stop when ad spend stops",
      "Better visibility in Google and AI search answers",
      "Monthly ranking and traffic reporting",
    ],
    process: [
      { title: "Technical Audit", description: "Crawl the site and prioritise indexing, speed and structure issues." },
      { title: "Keyword Strategy", description: "Map keywords to pages by intent and business value." },
      { title: "On-Page & Content", description: "Optimise existing pages and publish content that answers real questions." },
      { title: "Authority Building", description: "Earn relevant links and citations, then track and iterate monthly." },
    ],
    faqs: [
      { question: "How long does SEO take?", answer: "Most sites see meaningful movement within 60–90 days, with stronger compounding results over 6–12 months depending on competition." },
      { question: "Do you guarantee #1 rankings?", answer: "No honest agency can guarantee rankings. We commit to the work, transparent reporting and measurable progress." },
    ],
    ctaLabel: "Request SEO Proposal",
    whatsappMessage: "Hi HaadinGlobal, I want to improve my Google rankings.",
    seoTitle: "SEO Services (Technical, Local & Content SEO)",
    seoDescription: "Technical SEO, keyword strategy, content and link building to grow organic traffic. From PKR 35,000/month.",
    image: "/images/services/seo.jpg",
    featured: true,
    inBuilder: true,
    builderLabel: "Organic SEO",
    sortOrder: 3,
  },
  {
    slug: "social-media",
    title: "Social Media Ops",
    tagline: "Content & Brand",
    category: "CREATIVE",
    icon: "share",
    shortDescription:
      "End-to-end editorial calendar, custom static carousels, short-form reels editing, community management, and monthly analytics.",
    description:
      "Consistent, on-brand social media without the daily headache. We plan your content calendar, design posts and carousels, edit short-form reels, manage your community and report on what's working.",
    price: 30000,
    priceUnit: "MONTH",
    highlights: ["20 Posts / Mo", "8 Short Reels", "Audience DMs"],
    features: [
      "Monthly content calendar",
      "20 designed posts & carousels per month",
      "8 short-form reels per month",
      "Caption writing & hashtag research",
      "Community & DM management",
      "Monthly analytics report",
    ],
    benefits: ["A consistent brand presence", "More engagement and enquiries from followers", "Hours saved every week"],
    process: [
      { title: "Brand & Audience Review", description: "Understand your voice, audience and competitors." },
      { title: "Content Plan", description: "A monthly calendar approved by you before anything goes live." },
      { title: "Produce & Publish", description: "Design, edit and schedule every post and reel." },
      { title: "Engage & Report", description: "Reply to comments and DMs, then report monthly." },
    ],
    faqs: [
      { question: "Which platforms do you manage?", answer: "Facebook, Instagram, TikTok and LinkedIn are the most common; we tailor the mix to where your customers are." },
    ],
    ctaLabel: "Launch Content Engine",
    whatsappMessage: "Hi HaadinGlobal, let's discuss Social Media Management.",
    seoTitle: "Social Media Management",
    seoDescription: "Content calendars, designed posts, reels and community management. From PKR 30,000/month.",
    image: null,
    featured: false,
    inBuilder: true,
    builderLabel: "Social Media Mgmt",
    sortOrder: 4,
  },
  {
    slug: "web-development",
    title: "Web Development",
    tagline: "Full-Stack Digital",
    category: "TECH",
    icon: "code",
    shortDescription:
      "Bespoke responsive web apps, headless CMS integrations, custom Tailwind/React interfaces, and high-conversion landing pages.",
    description:
      "Your website is your 24/7 closer. We design and build fast, secure, mobile-first websites and web apps with clean code, lead capture wired into WhatsApp and your CRM, and SEO foundations built in.",
    price: 80000,
    priceUnit: "PROJECT",
    highlights: ["Sub-Second Load", "Figma to Code", "Mobile-First"],
    features: [
      "UX wireframes focused on conversion",
      "Custom Next.js / React development",
      "Mobile-first responsive design",
      "Lead forms connected to WhatsApp, email & CRM",
      "On-page SEO & structured data",
      "Deployment, SSL & analytics setup",
    ],
    benefits: ["Fast load times on mobile", "More enquiries from the same traffic", "A site you own and can grow"],
    process: [
      { title: "Wireframing & UX Flow", description: "Wireframes focused on conversion hierarchy and micro-copy." },
      { title: "Frontend Engineering", description: "Pixel-accurate components with strong mobile performance." },
      { title: "Tracking & Form Pipeline", description: "Forms and events wired into WhatsApp, email, Sheets or your CRM." },
      { title: "Deployment", description: "Global CDN deployment with SSL and monitoring." },
    ],
    faqs: [
      { question: "How long does a website take?", answer: "A focused marketing site typically takes 2–4 weeks; larger web apps are scoped individually." },
      { question: "Will I own the website?", answer: "Yes. You own the code, content and domain." },
    ],
    ctaLabel: "Get a Web Quote",
    whatsappMessage: "Hi HaadinGlobal, I need a modern web development quote.",
    seoTitle: "Website Development (Next.js, React & Landing Pages)",
    seoDescription: "Fast, mobile-first websites and web apps with lead capture and SEO built in. From PKR 80,000 per project.",
    image: null,
    featured: false,
    inBuilder: true,
    builderLabel: "Full-Stack Web Dev",
    sortOrder: 5,
  },
  {
    slug: "shopify",
    title: "Shopify Stores",
    tagline: "eCommerce Engineering",
    category: "TECH",
    icon: "shopping_bag",
    shortDescription:
      "Turnkey Shopify & Shopify Plus solutions, one-click checkout conversion, payment gateway setup, and speed tuning.",
    description:
      "Launch or rebuild a Shopify store that's built to sell: conversion-focused product pages, local payment options, a lean app stack and speed tuning so shoppers don't bounce.",
    price: 25000,
    priceUnit: "PROJECT",
    highlights: ["COD / Stripe / PayFast", "Upsell Logic", "App Stack"],
    features: [
      "Store setup & theme customisation",
      "Product, collection & navigation structure",
      "Payment gateways (COD, cards, local options)",
      "Upsell & cross-sell setup",
      "Speed optimisation",
      "Pixel & analytics integration",
    ],
    benefits: ["A store customers trust", "Higher conversion rates", "Easy day-to-day management"],
    process: [
      { title: "Store Plan", description: "Define catalogue, pages and payment requirements." },
      { title: "Design & Build", description: "Customise the theme and structure your products." },
      { title: "Integrations", description: "Payments, shipping, pixels and essential apps." },
      { title: "Launch & Tune", description: "Go live, test checkout and optimise speed." },
    ],
    faqs: [
      { question: "Can you migrate my existing store?", answer: "Yes — from WooCommerce or other platforms, including products, customers and redirects." },
    ],
    ctaLabel: "Build My Store",
    whatsappMessage: "Hi HaadinGlobal, let's build my Shopify e-commerce store.",
    seoTitle: "Shopify Store Development",
    seoDescription: "Conversion-focused Shopify stores with local payment gateways and speed tuning. From PKR 25,000 per project.",
    image: "/images/services/shopify.jpg",
    featured: false,
    inBuilder: true,
    builderLabel: "Shopify Scale",
    sortOrder: 6,
  },
  {
    slug: "ai-automation",
    title: "AI Automation",
    tagline: "Autonomous Systems",
    category: "TECH",
    icon: "smart_toy",
    shortDescription:
      "Custom Make/Zapier workflow automations, customer support GPT agents, CRM data routing, and auto lead qualification.",
    description:
      "Remove repetitive work from your team. We design automations that route leads, qualify enquiries, sync your tools and power AI assistants — so your people focus on selling and serving.",
    price: 80000,
    priceUnit: "PROJECT",
    highlights: ["Zapier / Make.com", "OpenAI API", "HubSpot / Sheets"],
    features: [
      "Workflow mapping & automation design",
      "Make.com / Zapier automations",
      "AI chat & support assistants",
      "Lead routing & qualification",
      "CRM & Google Sheets integrations",
      "Documentation & handover",
    ],
    benefits: ["Faster response to every lead", "Fewer manual errors", "Lower operating overhead"],
    process: [
      { title: "Process Mapping", description: "Document the workflow and where time is lost." },
      { title: "Design", description: "Choose tools and design the automation logic." },
      { title: "Build & Test", description: "Implement with real data and edge-case testing." },
      { title: "Handover", description: "Documentation, training and monitoring." },
    ],
    faqs: [
      { question: "Do I need technical knowledge?", answer: "No. We build, document and train your team; you just use the results." },
    ],
    ctaLabel: "Automate Operations",
    whatsappMessage: "Hi HaadinGlobal, I want to automate my business workflows.",
    seoTitle: "AI Automation & Workflow Systems",
    seoDescription: "Make.com, Zapier and AI assistant automations for lead routing, CRM sync and support. From PKR 80,000 per project.",
    image: null,
    featured: true,
    inBuilder: true,
    builderLabel: "AI Automated Pipelines",
    sortOrder: 7,
  },
  {
    slug: "youtube-automation",
    title: "YouTube Growth",
    tagline: "Video Authority",
    category: "CREATIVE",
    icon: "video_settings",
    shortDescription:
      "High-retention scriptwriting, dynamic video editing, voice sync, thumbnail CTR A/B tests, and full SEO metadata channel uploads.",
    description:
      "Build a YouTube channel that grows while you run your business. We handle research, scripting, editing, thumbnails and SEO-optimised uploads on a consistent schedule.",
    price: 40000,
    priceUnit: "MONTH",
    highlights: ["8 Long Videos / Mo", "A/B Thumbnails", "Tag Architecture"],
    features: [
      "Topic & keyword research",
      "Scriptwriting for retention",
      "Video editing & voice sync",
      "Thumbnail design & testing",
      "SEO titles, descriptions & tags",
      "Scheduled uploads & analytics",
    ],
    benefits: ["Consistent uploads", "Higher click-through and watch time", "A long-term content asset"],
    process: [
      { title: "Channel Strategy", description: "Niche, audience and content pillars." },
      { title: "Production", description: "Scripts, editing and thumbnails." },
      { title: "Publishing", description: "Optimised uploads on a fixed schedule." },
      { title: "Iteration", description: "Improve based on retention and CTR data." },
    ],
    faqs: [
      { question: "Do I have to appear on camera?", answer: "No — we can produce faceless, voice-over based content if you prefer." },
    ],
    ctaLabel: "Scale YouTube",
    whatsappMessage: "Hi HaadinGlobal, I'm interested in YouTube Automation.",
    seoTitle: "YouTube Automation & Channel Growth",
    seoDescription: "Scripting, editing, thumbnails and SEO uploads for consistent YouTube growth. From PKR 40,000/month.",
    image: "/images/services/youtube.jpg",
    featured: false,
    inBuilder: true,
    builderLabel: "YouTube Engine",
    sortOrder: 8,
  },
  {
    slug: "tiktok-ads",
    title: "TikTok Ad Sparks",
    tagline: "Gen-Z Conversion",
    category: "PERFORMANCE",
    icon: "play_circle",
    shortDescription:
      "Native UGC-style creator formats, viral trend hacking, spark ad amplification, and direct TikTok Pixel instant checkouts.",
    description:
      "Reach younger buyers where they spend their time. We produce native, UGC-style creatives and run TikTok campaigns with proper pixel tracking and fast creative iteration.",
    price: 15000,
    priceUnit: "MONTH",
    highlights: ["Hook Frameworks", "Spark Boosting", "Rapid Creative Iteration"],
    features: [
      "TikTok Pixel & events setup",
      "UGC-style creative production",
      "Spark Ads amplification",
      "Audience & interest testing",
      "Weekly creative refreshes",
      "Performance reporting",
    ],
    benefits: ["Lower CPMs than many platforms", "Creatives that feel native", "Fast learning cycles"],
    process: [
      { title: "Setup", description: "Pixel, events and account structure." },
      { title: "Creative Sprint", description: "Multiple hooks and formats ready for testing." },
      { title: "Launch", description: "Test audiences and creatives in parallel." },
      { title: "Scale", description: "Double down on winners and refresh fatigue." },
    ],
    faqs: [
      { question: "Is TikTok right for my business?", answer: "It works best for visual, consumer products and audiences under ~40. We'll tell you honestly if another channel is a better fit." },
    ],
    ctaLabel: "Run TikTok Ads",
    whatsappMessage: "Hi HaadinGlobal, I'm ready to run TikTok Ads.",
    seoTitle: "TikTok Ads Management",
    seoDescription: "UGC-style creatives and TikTok campaigns with pixel tracking and fast iteration. From PKR 15,000/month.",
    image: null,
    featured: false,
    inBuilder: true,
    builderLabel: "TikTok Viral Ads",
    sortOrder: 9,
  },
  {
    slug: "branding",
    title: "Branding & Identity",
    tagline: "Visual Distinction",
    category: "CREATIVE",
    icon: "auto_awesome",
    shortDescription:
      "Comprehensive visual architecture: primary/secondary marks, responsive typography systems, brand guidelines, and print assets.",
    description:
      "A brand people remember and trust. We create logos, colour and type systems, brand guidelines and the core assets you need to show up consistently everywhere.",
    price: 50000,
    priceUnit: "PROJECT",
    highlights: ["Complete Brandbook", "Figma Tokens", "Vector Kits"],
    features: [
      "Brand discovery workshop",
      "Primary & secondary logo marks",
      "Colour palette & typography",
      "Brand guidelines document",
      "Social media & stationery templates",
      "Source files in all formats",
    ],
    benefits: ["A professional first impression", "Consistency across every channel", "Assets your team can reuse"],
    process: [
      { title: "Discovery", description: "Audience, positioning and competitors." },
      { title: "Concepts", description: "Initial directions for your review." },
      { title: "Refinement", description: "Iterate on the chosen direction." },
      { title: "Delivery", description: "Guidelines and every file you need." },
    ],
    faqs: [
      { question: "How many logo concepts do I get?", answer: "Typically three initial directions, then refinements on the one you choose." },
    ],
    ctaLabel: "Establish Identity",
    whatsappMessage: "Hi HaadinGlobal, we need a complete brand identity.",
    seoTitle: "Branding & Logo Design",
    seoDescription: "Logos, brand guidelines and visual identity systems. From PKR 50,000 per project.",
    image: null,
    featured: false,
    inBuilder: true,
    builderLabel: "Identity & Brand",
    sortOrder: 10,
  },
  {
    slug: "content-writing",
    title: "Content Writing",
    tagline: "Semantic Copy",
    category: "CREATIVE",
    icon: "edit_note",
    shortDescription:
      "SEO-optimized thought leadership, conversion landing copy, nurture email drip sequences, and executive PR pieces.",
    description:
      "Words that rank and convert. We research and write blog articles, landing pages, emails and website copy in your brand voice — edited by humans and fact-checked.",
    price: 30000,
    priceUnit: "MONTH",
    highlights: ["10k Words / Mo", "Human-Edited", "Niche Research"],
    features: [
      "SEO blog articles",
      "Website & landing page copy",
      "Email sequences",
      "Product descriptions",
      "Keyword research & briefs",
      "Editing & fact-checking",
    ],
    benefits: ["Content that ranks", "Copy that converts", "A consistent brand voice"],
    process: [
      { title: "Brief", description: "Topics, keywords and voice agreed upfront." },
      { title: "Research & Draft", description: "Well-researched first drafts." },
      { title: "Edit", description: "Human editing and fact-checking." },
      { title: "Publish", description: "Formatted and optimised for publishing." },
    ],
    faqs: [
      { question: "Is the content AI-generated?", answer: "We may use AI tools for research, but every piece is written or rewritten, edited and fact-checked by a human." },
    ],
    ctaLabel: "Order Content",
    whatsappMessage: "Hi HaadinGlobal, I need content writing services.",
    seoTitle: "Content Writing & Copywriting",
    seoDescription: "SEO articles, website copy and email sequences written and edited by humans. From PKR 30,000/month.",
    image: null,
    featured: false,
    inBuilder: true,
    builderLabel: "Executive Copywriting",
    sortOrder: 11,
  },
  {
    slug: "graphic-design",
    title: "Graphic Design",
    tagline: "Visual Output",
    category: "CREATIVE",
    icon: "palette",
    shortDescription:
      "High-velocity on-demand graphics: social banners, packaging mockups, investor decks, email newsletters, and marketing prints.",
    description:
      "On-demand design for everything your marketing needs — social graphics, ads, presentations, packaging and print — delivered fast and on-brand.",
    price: 10000,
    priceUnit: "MONTH",
    highlights: ["Fast Turnaround", "Revisions Included", "Source Files"],
    features: [
      "Social media graphics",
      "Ad creatives",
      "Presentations & pitch decks",
      "Packaging mockups",
      "Print materials",
      "Source files included",
    ],
    benefits: ["Professional visuals on demand", "Consistent brand look", "No need for an in-house designer"],
    process: [
      { title: "Request", description: "Send a brief via WhatsApp or email." },
      { title: "Design", description: "First draft delivered quickly." },
      { title: "Revise", description: "Refine until it's right." },
      { title: "Deliver", description: "Final files in every format you need." },
    ],
    faqs: [
      { question: "How fast is delivery?", answer: "Most single graphics are delivered within 1–2 business days." },
    ],
    ctaLabel: "Subscribe to Design",
    whatsappMessage: "Hi HaadinGlobal, I'd like to subscribe to the Graphic Design pack.",
    seoTitle: "Graphic Design Services",
    seoDescription: "Social graphics, ad creatives, decks and print design on demand. From PKR 10,000/month.",
    image: null,
    featured: false,
    inBuilder: true,
    builderLabel: "Digital Design Suite",
    sortOrder: 12,
  },
];

export const SERVICE_CATEGORIES = [
  { value: "all", label: "All Services" },
  { value: "PERFORMANCE", label: "Performance Marketing" },
  { value: "TECH", label: "Development & Tech" },
  { value: "CREATIVE", label: "Creative & AI" },
] as const;

/** Deep-dive playbooks shown on /services (Stitch "Deep-Dive Focus Frameworks"). */
export const DEEP_DIVES = [
  {
    id: "deep-dive-meta",
    serviceSlug: "meta-ads",
    badge: "Deep Dive #1: Meta Performance",
    title: "The Meta Ads Growth Engine",
    intro: "Stop burning ad budgets on boost buttons. We engineer multi-tier funnels that scale profitable acquisition.",
    image: "/images/services/meta-ads.jpg",
    problem: "Ad fatigue, iOS tracking decay, rising CPMs, and non-converting creative assets draining monthly budgets.",
    solution: "Server-side Conversions API, dynamic product ads, and structured A/B creative testing cycles.",
    roadmapLabel: "4-Stage Deployment Roadmap",
    stats: [
      { label: "Typical Launch", value: "72 Hours" },
      { label: "Reporting", value: "Weekly" },
    ],
    ctaIcon: "chat",
  },
  {
    id: "deep-dive-web",
    serviceSlug: "web-development",
    badge: "Deep Dive #2: Web Architecture",
    title: "Next-Gen Web Platforms",
    intro: "Your website is your 24/7 digital closer. We build fast, secure web apps engineered for friction-free sales.",
    image: null,
    problem: "Bloated templates, slow 5-second load times, poor mobile responsiveness, and low conversions.",
    solution: "Clean hand-written code, a lightweight design system, mobile-first UX, and SEO built in from day one.",
    roadmapLabel: "4-Stage Development Sprint",
    stats: [
      { label: "Performance Target", value: "90+ Lighthouse" },
      { label: "Typical Turnaround", value: "14 Days" },
    ],
    ctaIcon: "terminal",
  },
] as const;
